# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2264d7f871a4a964814f0ac361ff812f7870eb65c5f79ad05abfeb6da83f13c6644004abf32ec72531266a10046c9f242021239413ccdfc36b1797670a18399

test:
  secret_key_base: bed5945df00075bf236e17266fecf4895a379c4b3104f480affec467c1b81ab8723531e94214241b9d968724511202a8cb817e292f5f78b180194d5e53066745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
